name: update task (priority -> 0-none)
method: PATCH
url: $NOTION_API_URL/pages/32eb7273944b80b28106f9c29f330007
body:
  content: |-
    {
      "properties": {
        "priority": {
          "id": "%3BYXd",
          "type": "select",
          "select": {
            "id": "5a12d048-4277-4349-b8f8-f05933562951",
            "name": "0",
            "color": "default"
          }
        }
      }
    }
  content_type: application/json
auth:
  type: bearer_token
  bearer_token:
    token: $NOTION_API_TOKEN
headers:
- name: Notion-Version
  value: $NOTION_VERSION
- name: content-type
  value: application/json
