name: query tasks done
method: POST
url: $NOTION_API_URL/data_sources/:projectTasksDsId/query
body:
  content: |-
    {
      "filter": {
        "and": [
          {
            "property": "status",
            "status": {
              "equals": "done"
            }
          },
          {
            "property": "@milestone",
            "relation": {
              "contains": "32fb7273944b80b3ad6ae7d261aff703"
            }
          }
        ]
      },
      "sorts": [
        { "property": "priority", "direction": "descending" },
        { "property": "created-at", "direction": "ascending" }
      ]
    }
  content_type: application/json
auth:
  type: bearer_token
  bearer_token:
    token: $NOTION_API_TOKEN
headers:
- name: Notion-Version
  value: $NOTION_VERSION
- name: content-type
  value: application/json
params:
- name: filter_properties[]
  value: task
- name: filter_properties[]
  value: type
- name: filter_properties[]
  value: priority
path_params:
- name: projectTasksDsId
  value: $NOTION_TASKS_DS_ID
